GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJQdXRyYTIiLCJlbWFpbCI6ImVtYWlsMzIxNEBnbWFpbC5jb20iLCJpYXQiOjE3MTc2ODEzNTgsImV4cCI6MTcxNzY4MTM3OH0.RXO2nj_rq-pfcbjhwBi8HN1KqnC8-SIeCKr6uJvYGe4

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Putra2",
    "email" : "email3214@gmail.com",
    "password" : "1234567",
    "confirmPassword" : "1234567"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "email3214@gmail.com",
    "password" : "1234567"
}

###
GET http://localhost:5000/token

###
DELETE  http://localhost:5000/logout